// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF0nAWZuNi6iBpSIBqbLzIexavwZ-a9m4',
    appId: '1:952342101616:web:6f454c0f4e9cc3f3f5feb5',
    messagingSenderId: '952342101616',
    projectId: 'login-30890',
    authDomain: 'login-30890.firebaseapp.com',
    databaseURL: 'https://login-30890-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-30890.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzQANckpWpKULLCTpRRFRawc34NDpZYaU',
    appId: '1:952342101616:android:990a55565d7922abf5feb5',
    messagingSenderId: '952342101616',
    projectId: 'login-30890',
    databaseURL: 'https://login-30890-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-30890.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvSijkyZD3CRvZfSKxCx1ZUD3rrS88hG4',
    appId: '1:952342101616:ios:75e74eca0bf22cb4f5feb5',
    messagingSenderId: '952342101616',
    projectId: 'login-30890',
    databaseURL: 'https://login-30890-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-30890.appspot.com',
    iosClientId: '952342101616-kb1umk8ukqjbabl5ca40venfehjnad4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.templates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvSijkyZD3CRvZfSKxCx1ZUD3rrS88hG4',
    appId: '1:952342101616:ios:d3b6f591e41541c5f5feb5',
    messagingSenderId: '952342101616',
    projectId: 'login-30890',
    databaseURL: 'https://login-30890-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-30890.appspot.com',
    iosClientId: '952342101616-civ0qa5a7fj6dhlci0vt7ht1hqui9klf.apps.googleusercontent.com',
    iosBundleId: 'com.example.templates.RunnerTests',
  );
}
